# Solution approach 2 - provide an efficient python solution with detailed inline comments explaining each step
def xorOperation(n, start):
    # Initialize result variable to 0, this will hold the final XOR result
    result = 0
    
    # Iterate over the range from 0 to n (exclusive)
    for i in range(n):
        # For each iteration, XOR the result with the current number in the sequence
        # The sequence is generated by adding 2 to the start number for each iteration
        result ^= (start + 2 * i)
    
    # Return the final XOR result
    return result